### ISSUE TITLE
RegEx does not match some CPE string

### ISSUE THREAD

**Issue by adubaldo** [Rev3rseSecurity/WebMap#10]
The function `checkCVE()` within the `async.js:34` file contains a RegEx that does not match some CPE strings.

```javascript 
if(/^cpe:.+:.+:.+:.*$/.test(cpestr)) {
```

Example:
**OK:** `cpe:/a:openbsd:openssh:7.8p1`
**NOK**: `cpe:/a:microsoft:systems_management_server`
**NOK**: `cpe:/o:linux:linux_kernelcpe `

**Comment by theMiddleBlue** [comment]
Hi @adubaldo 

`checkCVE()` checks only those CPE that includes a version number (as described on the README, maybe I need to explain it better). This in order to prevent false positives and a lot of CVE that are not related to the service found by nmap.
