### ISSUE TITLE
suggested structural improvement (IMHO)

### ISSUE THREAD

**Issue by c0rv00** [Rev3rseSecurity/WebMap#11]
in views.py set variables only and not html code in r dictionary.

```
r['pretable'] = ''
	if filterservice == "" and filterportid == "":
		r['hostup'] = str(hostsup)		        # Host up counter
		r['open_port'] = str(ports['open'])		# Open port counter
		r['closed_port'] = str(ports['closed'])	# Closed port counter

[...]

return render(request, 'nmapreport/index.html', r)
```
-------------------------------------------------------------------------------------------------------
in index.html instead insert variables with {{ var }} 
[ ... ] 
`<span class="blue-text">`{{ hostup }}`</span>`
[ ... ]
in this way:
- make it lighter and more readable python code. 
- debugging is easier
- avoid string concatenation of html code in views.py
- all html code regains correction editor benefits

**Comment by theMiddleBlue** [comment]
Hi @c0rv00 

this is right. I'm working on a better django template in order to avoid it, maybe on the v3. Thanks for reporting this!
