### ISSUE TITLE
Application freeze with 'cpe:/o' generic CPE

### ISSUE THREAD

**Issue by adubaldo** [Rev3rseSecurity/WebMap#12]
example: 

> api.py:116

```javascript
...
requests.get('http://cve.circl.lu/api/cvefor/cpe:/o:microsoft:windows')
...
```

retrieve a response of **78MB** (maybe more) and will produce a list of  thousand of  CVEs, slowing down the app, or worse freezing it.

If not relevant to our port scan, **avoiding `cpe:/o:` queries** (wich stand for operativ system CPE) will probably  solve the problem.

![image](https://user-images.githubusercontent.com/17628687/47619963-9f036a80-dae4-11e8-8664-d55f64ef9ebc.png)

**Comment by theMiddleBlue** [comment]
this should not happen because `/cpe:/o:microsoft:windows` should be excluded by the `checkCVE()` function because it not includes a version number. Have you tested it using the current v2/master?
