### ISSUE TITLE
Errors Out When Loading XML File

### ISSUE THREAD

**Issue by jgamblin** [Rev3rseSecurity/WebMap#2]
Following the instructions when I try to load the XML I get this error: 
http://dpaste.com/2EVSCH9 

Running: Version 18.06.1-ce-mac73 (26764) on MacOS

**Comment by jgamblin** [comment]
[nmap.pdf](https://github.com/Rev3rseSecurity/WebMap/files/2508710/nmap.pdf)

^ Full Error Message.

**Comment by theMiddleBlue** [comment]
thanks for reporting this @jgamblin 
could you share the XML file? Or eventually share the nmap command that you're used to generate it?

**Comment by jgamblin** [comment]
[myscan2.txt](https://github.com/Rev3rseSecurity/WebMap/files/2510465/myscan2.txt)
 
nmap -sV --resolve-all --open -oX /tmp/webmap/myscan2.xml jerrygamblin.com

**Comment by theMiddleBlue** [comment]
Thanks @jgamblin 

unfortunately I can't reproduce your issue:

![image](https://user-images.githubusercontent.com/4454961/47436542-f3d27880-d7a6-11e8-87a3-75dc2ece8b6c.png)

could you try to remove your current webmap docker image and try again? There was a couple of commit in the last days in order to fix 2 bugs on the XML parser.

**Comment by jgamblin** [comment]
Doing some more testing today the error happens if I have an active NMap scan running and attempt to load the web interface.  Once the scan is complete it works perfectly.

**Comment by 0xSeanG** [comment]
I seem to be having a similar error as @jgamblin. 
as of 31OCT18:
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
rev3rse/webmap      latest              84dee9f4f3be        5 days ago          1.07GB

nmap scan args: nmap -sT -T4 -oX /tmp/webmap/myscan2.xml scanme.nmap.org

PDF of full error: [error.pdf](https://github.com/Rev3rseSecurity/WebMap/files/2534977/error.pdf)
