### ISSUE TITLE
Unable to Install on kali | both with docker or django standalone 

### ISSUE THREAD

**Issue by SynAckPwn23** [Rev3rseSecurity/WebMap#23]
Can you please provide clear instruction? What is reported in README it doesn't work.
Thx

**Comment by theMiddleBlue** [comment]
Hi @SynAckPwn23 

what kind of issue/error you had on kali? I'm running it without problems. I've just installed docker and run `curl -sL http://bit.ly/webmapsetup | bash`:

![image](https://user-images.githubusercontent.com/4454961/48299053-cb958a00-e4c7-11e8-8e81-3de0944e4ca1.png)

**Comment by SynAckPwn23** [comment]
[image: Schermata 2018-11-10 alle 11.36.00.png]
hi,
attached my screenshot probably something in port forwarding is not working
for me..

thx
Daniele

Il giorno sab 10 nov 2018 alle ore 09:06 theMiddle <notifications@github.com>
ha scritto:

**Comment by theMiddleBlue** [comment]
@SynAckPwn23 I can't see your screenshot from github :/

**Comment by SynAckPwn23** [comment]
Ok, in any case this is the situation: The bash script terminate correctly but when I try http://127.0.0.1:8000 I got “Unable to connect” message from Firefox..

Inviato da iPhone

**Comment by SynAckPwn23** [comment]
Here it is:

root@kali:~# docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED
         STATUS                   PORTS               NAMES
bd38565149d3        rev3rse/webmap      "python3 /opt/nmapda…"   5 hours
ago         Exited (1) 5 hours ago                       webmap
root@kali:~# docker inspect webmap
[
    {
        "Id":
"bd38565149d3573d2beb4b51d03d091836d6871054393f7f0c188a6af893baf0",
        "Created": "2018-11-10T10:34:17.388283557Z",
        "Path": "python3",
        "Args": [
            "/opt/nmapdashboard/manage.py",
            "runserver",
            "0:8000"
        ],
        "State": {
            "Status": "exited",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 1,
            "Error": "",
            "StartedAt": "2018-11-10T10:34:18.295923644Z",
            "FinishedAt": "2018-11-10T10:34:18.283949453Z"
        },
        "Image":
"sha256:cb76381d77bbc6cccc94543a629368f1b4916868e4f6164ac9d89405e137a4a8",
        "ResolvConfPath":
"/var/lib/docker/containers/bd38565149d3573d2beb4b51d03d091836d6871054393f7f0c188a6af893baf0/resolv.conf",
        "HostnamePath":
"/var/lib/docker/containers/bd38565149d3573d2beb4b51d03d091836d6871054393f7f0c188a6af893baf0/hostname",
        "HostsPath":
"/var/lib/docker/containers/bd38565149d3573d2beb4b51d03d091836d6871054393f7f0c188a6af893baf0/hosts",
        "LogPath":
"/var/lib/docker/containers/bd38565149d3573d2beb4b51d03d091836d6871054393f7f0c188a6af893baf0/bd38565149d3573d2beb4b51d03d091836d6871054393f7f0c188a6af893baf0-json.log",
        "Name": "/webmap",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "docker-default",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/tmp/webmap:/opt/xml"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {
                "8000/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "8000"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "shareable",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/asound",
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir":
"/var/lib/docker/overlay2/eafac76d5c62efd717f05a04676cb2ef3ca1e1289e3d8f452d06b032baf736ee-init/diff:/var/lib/docker/overlay2/5ec93d05d0ee807aa87f92f776fd49352e0beab2ff4d2c27f45fbec7c1565c6f/diff:/var/lib/docker/overlay2/579fd8b8d6ac210f901e30a5edb32ea5cfb97c234cd066acc6b162f6a86dde01/diff:/var/lib/docker/overlay2/9f335c5bdcef0222563a98d21a21bd945bde6f373e9a70e44a39cc3f555be1d0/diff:/var/lib/docker/overlay2/135a4aaf870626186c9df77f8d793c1eb3c69fa64f4d994a6df5ad55f1b60f7f/diff:/var/lib/docker/overlay2/c1f5d78758b1ae1f673e6ec643b9cc8c5403514ba0b8c9af07546d31e415ab95/diff:/var/lib/docker/overlay2/ee645b234a4c74dd9c3728642ff3a2664737ba9f8e82d5c99c023641d2b820b0/diff:/var/lib/docker/overlay2/4353df3f5f911014c3231df6b7195fd7fa59770aeb0d301e945ae990e0dc162f/diff:/var/lib/docker/overlay2/715aad8d723ca320fa0dd1dc77cba1e4b1701e7239c44bb3242bd3d750cb289f/diff:/var/lib/docker/overlay2/1c8edb1fbb6a7d125ebd325683e32ece3ff62d6f20d7831ead1992d52d9da999/diff:/var/lib/docker/overlay2/d60372b591281ec8b4898154eff8506555a564995faefa9a4f025bba0b8fd1ed/diff:/var/lib/docker/overlay2/a8c5dde7af1817eeb8ed77fa32de674a90e16349e592fecbd632414760ae635e/diff",
                "MergedDir":
"/var/lib/docker/overlay2/eafac76d5c62efd717f05a04676cb2ef3ca1e1289e3d8f452d06b032baf736ee/merged",
                "UpperDir":
"/var/lib/docker/overlay2/eafac76d5c62efd717f05a04676cb2ef3ca1e1289e3d8f452d06b032baf736ee/diff",
                "WorkDir":
"/var/lib/docker/overlay2/eafac76d5c62efd717f05a04676cb2ef3ca1e1289e3d8f452d06b032baf736ee/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/tmp/webmap",
                "Destination": "/opt/xml",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "webmap",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "8000/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [

"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": null,
            "ArgsEscaped": true,
            "Image": "rev3rse/webmap",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": [
                "python3",
                "/opt/nmapdashboard/manage.py",
                "runserver",
                "0:8000"
            ],
            "OnBuild": null,
            "Labels": {}
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID":
"f464ab1239b28383120600f14c311973c91f18d7e77ac0d7e9d65b2518f5f3c4",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/f464ab1239b2",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID":
"7e45c9b7fc8c45a03f8ec3afe12289d84ca942c889791e38b68e63cccd8da5ad",
                    "EndpointID": "",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "",
                    "DriverOpts": null
                }
            }
        }
    }
]


Il giorno sab 10 nov 2018 alle ore 16:28 theMiddle <notifications@github.com>
ha scritto:

**Comment by theMiddleBlue** [comment]
ok, it's stopped. It could happen when something already listen on 8000. Could you try this?

```bash
docker run -d --name webmap2 -h webmap -p 8123:8000 -v /tmp/webmap:/opt/xml rev3rse/webmap
```

and then open you browser to [http://localhost:8123](http://localhost:8123)

**Comment by theMiddleBlue** [comment]
What about: docker logs webmap
?

**Comment by SynAckPwn23** [comment]
exec user process caused "exec format error"


Il giorno sab 10 nov 2018 alle ore 21:53 theMiddle <notifications@github.com>
ha scritto:

**Comment by theMiddleBlue** [comment]
OMG, I really don't know why it happens... Can you try this?

```
docker run -ti --name webmap3 -v /tmp/webmap:/opt/xml -p 8000:8000 --entrypoint /bin/bash rev3rse/webmap

python3 /opt/nmapdashboard/manage.py runserver 0:8000
```

then point your browser to [http://localhost:8000](http://localhost:8000)

**Comment by theMiddleBlue** [comment]
on kali:
```bash
# uname -a
Linux emmetbrown 4.12.0-kali1-amd64 #1 SMP Debian 4.12.6-1kali6 (2017-08-30) x86_64 GNU/Linux
# docker --version
Docker version 17.05.0-ce, build 89658be
```

on macos:
```bash
docker --version
Docker version 18.03.1-ce, build 9ee9f40
```

**Comment by theMiddleBlue** [comment]
just another test:

```bash
$ docker pull ubuntu:latest
$ git clone https://github.com/Rev3rseSecurity/WebMap.git
$ cd WebMap/
$ cd docker/
$ docker build --no-cache -t webmaptest .
$ docker run -d -v /tmp/webmap:/opt/xml -p 8000:8000 webmaptest
```

it could take a while

**Comment by SynAckPwn23** [comment]
In this way with ubuntu environment it works...


Il giorno dom 11 nov 2018 alle ore 02:44 theMiddle <notifications@github.com>
ha scritto:

**Comment by theMiddleBlue** [comment]
perfect! I'll add this installation method to the README

thanks.
