### ISSUE TITLE
PDF generation never end

### ISSUE THREAD

**Issue by SynAckPwn23** [Rev3rseSecurity/WebMap#24]
It seems that the PDF generation is not working. 
PDF not ready yet...
PDF not ready yet...
PDF not ready yet...
PDF not ready yet...
PDF not ready yet...
PDF not ready yet...
PDF not ready yet...
(still in this status for very very long time) with not so much big .xml file.

Do you have any idea?
Thanks, Daniele

**Comment by theMiddleBlue** [comment]
uhm... I suspect that it's related to wkhtml2pdf version, in the docker container there's the amd64 version. Based on your `uname` output, it seems that you're running on a 32bit system, right? Probably I need to create a "32bit compatible" version of the docker image...

Anyway, if you want to try to change the wkhtml2pdf version, you should take a shell on the container with `docker exec -ti webmap /bin/bash` and replace the wkhtml2pdf in /opt/ with the 32bit version, probably this: [https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.4/wkhtmltox-0.12.4_linux-generic-i386.tar.xz](https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.4/wkhtmltox-0.12.4_linux-generic-i386.tar.xz)

**Comment by blockchainsecure** [comment]
You'll be redirected to the PDF Report:
PDF not ready yet...
PDF not ready yet...
PDF not ready yet...
PDF not ready yet...
PDF not ready yet...
PDF not ready yet...
PDF not ready yet...
PDF not ready yet...
PDF not ready yet...
PDF not ready yet...
PDF not ready yet...
PDF not ready yet...
PDF not ready yet...
PDF not ready yet...
PDF not ready yet...
PDF not ready yet...
PDF not ready yet...
PDF not ready yet...
PDF not ready yet...
PDF not ready yet...
PDF not ready yet...
PDF not ready yet...
PDF not ready yet...
PDF not ready yet...
PDF not ready yet...
PDF not ready yet...
PDF not ready yet...
PDF not ready yet...
PDF not ready yet...
PDF not ready yet...
PDF not ready yet...
PDF not ready yet...
PDF not ready yet...
PDF not ready yet...
PDF not ready yet...
PDF not ready yet...
PDF not ready yet...
PDF not ready yet...
PDF not ready yet...

**Comment by theMiddleBlue** [comment]
Hi @blockchainsecure 
can you provide us more information about your system and docker?
