### ISSUE TITLE
KeyError at /

### ISSUE THREAD

**Issue by tailh-vnsec** [Rev3rseSecurity/WebMap#26]
**Describe the bug**
When I copy an .xml file to /tmp/webmap and refresh the WebMap interface, I get the following error message:

```
Request Method: | GET
-- | --
http://localhost:8000/
2.1.3
KeyError
'service'
/opt/nmapdashboard/nmapreport/functions.py in nmap_ports_stats, line 83
/usr/bin/python3
3.6.6
['/opt/nmapdashboard',  '/usr/lib/python36.zip',  '/usr/lib/python3.6',  '/usr/lib/python3.6/lib-dynload',  '/usr/local/lib/python3.6/dist-packages',  '/usr/lib/python3/dist-packages']
Tue, 13 Nov 2018 15:00:21 +0000
```

**To Reproduce**
Steps to reproduce the behavior, including the Nmap syntax used:

1. Nmap syntax: 
nmap -vv -p 113,1465,4410,4749,5619,9434,13167,15763,18829,22738,25758,30475,32124,32605,32836,35750,36829,37148,37259,38436,39153,43806,44802,48617,51420,51932,51981,64170 -A -Pn --script vuln -oA 192.168.200.225 192.168.200.225/32

2. WebMap in docker container: [x] Yes / [ ] No
3. WebMap version or branch: v2.1/master

**Please see the attached .pdf file for more details**
[KeyError at _.pdf](https://github.com/Rev3rseSecurity/WebMap/files/2576915/KeyError.at._.pdf)

**You also try with my xml file for the same error**
**Note**: change this file into 192.168.200.225.xml and copy it on /tmp/webmap
[192.168.200.225.log](https://github.com/Rev3rseSecurity/WebMap/files/2576934/192.168.200.225.log)

**Comment by theMiddleBlue** [comment]
Thanks @tailh-vnsec 

I've reproduced your issue, thank you for attaching your XML file. I'm working on it, I'll keep you in touch here.

thanks!

**Comment by theMiddleBlue** [comment]
hi @tailh-vnsec 

I think I've fixed with the latest commit. Could you try to update your webmap docker images as described here? [https://github.com/Rev3rseSecurity/WebMap#usage](https://github.com/Rev3rseSecurity/WebMap#usage)

**Comment by tailh-vnsec** [comment]
Hi theMiddleBlue,

I used  `$ docker pull rev3rse/webmap` to update webmap docker images and restart it, but it's not working. It still has the same error as above.

[KeyError at _.zip](https://github.com/Rev3rseSecurity/WebMap/files/2577408/KeyError.at._.zip)

**Comment by tailh-vnsec** [comment]
> hi @tailh-vnsec
> 
> I think I've fixed with the latest commit. Could you try to update your webmap docker images as described here? https://github.com/Rev3rseSecurity/WebMap#usage

Hi theMiddleBlue,

I used  `$ docker pull rev3rse/webmap` to update webmap docker images and restart it, but it's not working. It still has the same error as above.

[KeyError at _.zip](https://github.com/Rev3rseSecurity/WebMap/files/2577408/KeyError.at._.zip)

**Comment by theMiddleBlue** [comment]
I think that you need to pull the new image and create a brand new container. I tried your xml file with the latest image and it seems work fine. Could you try this?

```
docker stop webmap
docker rm webmap
docker pull rev3rse/webmap
curl -sL http://bit.ly/webmapsetup | bash
```

**Comment by tailh-vnsec** [comment]
> I think that you need to pull the new image and create a brand new container. I tried your xml file with the latest image and it seems work fine. Could you try this?
> 
> ```
> docker stop webmap
> docker rm webmap
> docker pull rev3rse/webmap
> curl -sL http://bit.ly/webmapsetup | bash
> ```

It worked.

Thanks for your support.
