### ISSUE TITLE
Details without Service name

### ISSUE THREAD

**Issue by daniel2005d** [Rev3rseSecurity/WebMap#34]
When u try open a details for port and that not have service identification, the app handle an error. I'm patched in views.py line 425, 

425           if 'service' in p:
426                if filterservice != "" and p['service']['@name'] == filterservice:
427                    striggered = True

**Comment by theMiddleBlue** [comment]
Hi @daniel2005d 

thanks for reporting this. This issue is already fixed on 2.2/master version, and the new webmap 2.2 docker image will be available soon on dockerhub. I'll close this issue when done.

Thanks!

**Comment by theMiddleBlue** [comment]
hi @daniel2005d 

the v2.2 is out, can you try to reinstall WebMap? with:
`curl -sL http://bit.ly/webmapsetup | bash`

let me know if it solves your issue.
