### ISSUE TITLE
Application error on loading detailed xml's

### ISSUE THREAD

**Issue by migueljtc** [Rev3rseSecurity/WebMap#42]
I'm getting django errors (looks like xml parsing related) when importing nmap xml files.
These files were made in zenmap and exported to xml (zenmap should be the same as nmap).

The nmap command is "nmap -sS -sU -T4 -A -v -PE -PP -PS80,443 -PA3389 -PU40125 -PY -g 53 --script "default or (discovery and safe)" 192.168.1.0/24"

This is the "Slow comprehensive scan" option.

**Comment by theMiddleBlue** [comment]
Hi @migueljtc 

could you provide more information about the error and/or share your xml file?

thank you

**Comment by migueljtc** [comment]
@theMiddleBlue 
Unfortunately I cannot provide with the netmap scan due to professional issues.  I'll try to show the error since we're using it in production (yes I've read the warning) but will take some time to do the proper backups.

What I've noticed is zenmap (nmap with gui basically) large network scans with "comprehensive" profile flags (ex; **nmap -sS -sU -T4 -A -v -PE -PP -PS80,443 -PA3389 -PU40125 -PY -g 53 --script "default or (discovery and safe)" 192.168.1.0/24**) do an xml/parsing error. I'll provide the error ASAP.

**Comment by migueljtc** [comment]
Here's an error after running the nmap with the following flags:

> -A -sT -T3 -sU

Error:
> TypeError at /
> list indices must be integers or slices, not str
> Request Method:	GET
> Request URL:	http://192.168.164.238:8000/
> Django Version:	2.1.3
> Exception Type:	TypeError
> Exception Value:	
> list indices must be integers or slices, not str
> Exception Location:	/opt/nmapdashboard/nmapreport/views.py in index, line 636
> Python Executable:	/usr/bin/python3
> Python Version:	3.6.7
> Python Path:	
> ['/opt/nmapdashboard',
>  '/usr/lib/python36.zip',
>  '/usr/lib/python3.6',
>  '/usr/lib/python3.6/lib-dynload',
>  '/usr/local/lib/python3.6/dist-packages',
>  '/usr/lib/python3/dist-packages']
> Server time:	Wed, 5 Dec 2018 15:43:14 +0000

**Comment by theMiddleBlue** [comment]
could you check if the new v2.3 fixes this issue? If you need help with the upgrade, please refer to the README file.

**Comment by migueljtc** [comment]
Using the flags "-A -sT -T3 -sU"  it work properly! Solved.

**Comment by theMiddleBlue** [comment]
thanks @migueljtc
