### ISSUE TITLE
WebMap not detecting nmap scans in /tmp/webmap

### ISSUE THREAD

**Issue by Clutchisback1** [Rev3rseSecurity/WebMap#48]
**Describe the bug**
For whatever reason, I can't seem to get webmap to detect the nmap scans placed into /tmp/webmap. I'm attempting to use the "quick and dirty" method and the normal method below. I'm  able to get the gui interface up and running on port 8000 and everything just fine however no nmap scans ever populate in spite of placing them in the /tmp/webmap directory. 

My assumption is that /tmp/webmap isn't actually the web-root somehow. 

**To Reproduce**
Steps to reproduce the behavior, including the Nmap syntax used:

$ mkdir /tmp/webmap
$ docker run -d \
         --name webmap \
         -h webmap \
         -p 8000:8000 \
         -v /tmp/webmap:/opt/xml \
         rev3rse/webmap

$ # now you can run Nmap and save the XML Report on /tmp/webmap
$ nmap -sT -A -T4 -oX /tmp/webmap/myscan.xml 192.168.1.0/24

**Expected behavior**
I expected when I went to localhost:8000 that the nmap scan saved there would be displayed on the web interface. I've also ensured that the permissions on my scans were set to +x in case I was facing permissions issues.

**Screenshots**

![webmap](https://user-images.githubusercontent.com/6752796/49700690-6bb20200-fb9f-11e8-9ef8-3ea7c9df7bb1.png)

**Comment by Clutchisback1** [comment]
I'm super invested in getting this to work as WebMap would be great to use for reports!

I also forgot to mention that I am using Ubuntu 18.

**Comment by theMiddleBlue** [comment]
Hi @Clutchisback1 

this is really odd, could you provide the output of the following commands?
```
docker exec -ti webmapdev ls -la /opt/xml
docker inspect webmap
```

thank you.

**Comment by Clutchisback1** [comment]
This is the output for both of those commands:

sudo docker inspect webmap
Error: No such container: webmapdev
[
    {
        "Id": "e86e9fd253096e308d05decc2cfd5f42f7683b5eb1c8306dc19e1ec608355237",
        "Created": "2018-12-09T17:32:18.006384241Z",
        "Path": "bash",
        "Args": [
            "/startup.sh"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 6830,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2018-12-09T17:32:18.675403919Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:a6031bb81f9d769a2ce78cb433e391159abd29948a9bd6c2c3dc4bfe991faac2",
        "ResolvConfPath": "/var/snap/docker/common/var-lib-docker/containers/e86e9fd253096e308d05decc2cfd5f42f7683b5eb1c8306dc19e1ec608355237/resolv.conf",
        "HostnamePath": "/var/snap/docker/common/var-lib-docker/containers/e86e9fd253096e308d05decc2cfd5f42f7683b5eb1c8306dc19e1ec608355237/hostname",
        "HostsPath": "/var/snap/docker/common/var-lib-docker/containers/e86e9fd253096e308d05decc2cfd5f42f7683b5eb1c8306dc19e1ec608355237/hosts",
        "LogPath": "/var/snap/docker/common/var-lib-docker/containers/e86e9fd253096e308d05decc2cfd5f42f7683b5eb1c8306dc19e1ec608355237/e86e9fd253096e308d05decc2cfd5f42f7683b5eb1c8306dc19e1ec608355237-json.log",
        "Name": "/webmap",
        "RestartCount": 0,
        "Driver": "aufs",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "docker-default",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/tmp/webmap:/opt/xml"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {
                "8000/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "8000"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "shareable",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/asound",
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": null,
            "Name": "aufs"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/tmp/webmap",
                "Destination": "/opt/xml",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "webmap",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "8000/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "DEBIAN_FRONTEND=noninteractive"
            ],
            "Cmd": null,
            "ArgsEscaped": true,
            "Image": "rev3rse/webmap",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": [
                "bash",
                "/startup.sh"
            ],
            "OnBuild": null,
            "Labels": {}
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "84c3707bfabcffd2da0f74d7f89ff06ddaf653439f48dcbe49f0cea147b5fc1d",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "8000/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "8000"
                    }
                ]
            },
            "SandboxKey": "/var/snap/docker/321/run/docker/netns/84c3707bfabc",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "d164075a3fc76b1eddf0d453f6821bb24b6eceb34d80b7a6382d9443dfe79371",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.17.0.2",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "02:42:ac:11:00:02",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "498f94734aabf960a397deb12c566b999c2266711140a003f70cbe7d5db34841",
                    "EndpointID": "d164075a3fc76b1eddf0d453f6821bb24b6eceb34d80b7a6382d9443dfe79371",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:11:00:02",
                    "DriverOpts": null
                }
            }
        }
    }
]

**Comment by theMiddleBlue** [comment]
the first command has a wrong docker container name (my mistake, sorry), it should be:

`docker exec -ti webmap ls -la /opt/xml`

thanks

**Comment by Clutchisback1** [comment]
Output of that command:

➜  ~ sudo docker exec -ti webmap ls -la /opt/xml


[sudo] password for clutchisback1: 
total 8
drwxr-xr-x  2 root root 4096 Dec  9 16:21 .
drwxr-xr-x 10 root root 4096 Dec  9 17:32 ..

**Comment by Clutchisback1** [comment]
Is there supposed to be an xml dir in /opt/?

**Comment by theMiddleBlue** [comment]
@Clutchisback1 yes, in your inspect output I can see that /tmp/webmap is mounted on /opt/xml inside the webmap container. From your inspect output:
```
"Mounts": [
            {
                "Type": "bind",
                "Source": "/tmp/webmap",
                "Destination": "/opt/xml",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
```
this should let your webmap able to read Nmap XML files just by putting it on /tmp/webmap/ on your main host...

Have you tried to run a Nmap scan from webmap by clicking on the "new nmap scan" button?

**Comment by Clutchisback1** [comment]
Yes! However clicking on the button does nothing. I've tried in multiple browsers.

**Comment by Clutchisback1** [comment]
I'll do some more trouble shooting today and see if I can figure something out. Let me know if you need to see more output. I appreciate all the support so far!!

**Comment by Clutchisback1** [comment]
**GOT IT FIXED!!!!!**

Well more like figured out how to get it to work. *It may be important to note that I also used the root account to do all of this while testing* I was also having this issue on Ubuntu 18 if that helps anyone:


## Steps to reproduce the work-around:

Run the launch commands as instructed in the ReadMe:

    $ mkdir /tmp/webmap
    $ docker run -d \
        --name webmap \
         -h webmap \
         -p 8000:8000 \
         -v /tmp/webmap:/opt/xml \
         rev3rse/webmap

    $ # now you can run Nmap and save the XML Report on /tmp/webmap
    $ nmap -sT -A -T4 -oX /tmp/webmap/myscan.xml 192.168.1.5


I then used the command `docker exec -t -i webmap /bin/bash` to interact with to docker after launching it. Your prompt hostname should change to `webmap` as a result of you now being on the docker.

![image](https://user-images.githubusercontent.com/6752796/49845867-cb6a0200-fd85-11e8-99f4-26fd93d0e0a8.png)

Now that you're here you need to (find a way) copy your scan in `/tmp/webmap/` to the docker in the directory `/opt/xml` There is probably an easier way to do this but on the docker there isn't a `VIM` or `nano` so I took the XML scan output and base64 encoded it (again probably a much easier way to get this scan on the docker); then I echoed it to a file in `/opt/xml/myscan.xml` by doing:

`echo 'put base64 scan output here ' | base64 -d > /opt/xml/myscan.xml`

I also changed the file perms to +x by doing:

`chmod 777 /opt/xml/myscan.xml`

Finally, I restarted the docker by doing `docker reset` and navigated to `localhost:8000` and saw my scan sitting there.

I guess the conclusion was that for some reason the docker didn't have access to or for whatever reason isn't able to read from `/tmp/webmap` on my local file system. 

Thanks @theMiddleBlue for the support! I love your product and will be using this on my future engagements! Thanks for working on this one with me!
