### ISSUE TITLE
Application error on view nmap xml file 'KeyError at / 'scaninfo''

### ISSUE THREAD

**Issue by danyfu** [Rev3rseSecurity/WebMap#49]
**Describe the bug**
After click to the view button to see the detailed info off my nmap scan file, the webapp throws an error.

**To Reproduce**
Steps to reproduce the behavior, including the Nmap syntax used:

1. Nmap syntax: nmap -sP scanme.nmap.org -oX /tmp/webmap/network_port_discovery.xml
2. WebMap in docker container: [x] Yes / [ ] No
3. WebMap version or branch: v2.2/master (docker hub image_id: a6031bb81f9d)
3. Step to reproduce:  Import a xml file, and load it, when click on xml file name link, the wrong happen.

**Expected behavior**
Show the detailed information of the nmap scan.

**Screenshots**
![image](https://user-images.githubusercontent.com/9112457/49977097-d180ef80-fef9-11e8-9df7-e0c055d05dd7.png)

![image](https://user-images.githubusercontent.com/9112457/49977114-e52c5600-fef9-11e8-9d7f-c1b457591823.png)

Here is the file with the detailed ouput for that error: [KeyError.at.scaninfo.pdf](https://github.com/Rev3rseSecurity/WebMap/files/2678260/KeyError.at.scaninfo.pdf)

**Additional context**
Great project, very useful!

**Comment by theMiddleBlue** [comment]
thank you @danyfu 

I've reproduced this bug and I'm fixing it on the 2.3 that will be online soon.
Thanks!

**Comment by danyfu** [comment]
Is there a workaround solution that I can implement before this new patch realease?

**Comment by theMiddleBlue** [comment]
could you check if the new v2.3 fixes this issue? If you need help with the upgrade, please refer to the README file.

**Comment by danyfu** [comment]
Yes it fixes that error, thanks!

I notice that the generated reports on the previous version cause an error when I export to PDF, but after delete them and run again with the same command it exports correctly.

I'm testing it the results using also a module called vulscan (https://github.com/scipag/vulscan), and works fine.

**Comment by danyfu** [comment]
Ok I'm notice with multihost scan sometimes throw me the error 'scaninfo', that I was show you before, but now on the view _/view/pdf_.

Here is an attachment of the result.
[scaninfo_view_pdf_error.pdf](https://github.com/Rev3rseSecurity/WebMap/files/2688026/scaninfo_view_pdf_error.pdf)

**Comment by theMiddleBlue** [comment]
thanks @danyfu 

I've just updated the docker image on dockerhub, now it should work (and it shouldn't show any results).
