### ISSUE TITLE
Token Bug

### ISSUE THREAD

**Issue by monrorMe** [Rev3rseSecurity/WebMap#59]
**Describe the bug**
I get this every time I go to use webmap.  Just started and not sure why,

<img width="560" alt="screen shot 2018-12-17 at 2 26 28 pm" src="https://user-images.githubusercontent.com/3006836/50110264-d0a4d200-0207-11e9-9759-5622b906838a.png">

**Token

Generate a new token with:
docker exec -ti webmap /root/token**

**To Reproduce**
Steps to reproduce the behavior, including the Nmap syntax used:

Not sure.  I go to the localhost:8000 

**Expected behavior**
I expect the webgui to appear.
**Screenshots**

**Additional context**

**Comment by danyfu** [comment]
You need to generate the token to access to the WebUI, this is a new feature on the recent release.

To get the token, open a terminal on the host that you installed webmap, and execute the command with sudo privileges.

`docker exec -ti webmap /root/token`

After you run the command it would show the token to acess to the WebUI:
> Token: dQa9o55OQcBH

**Comment by monrorMe** [comment]
I have done it about 10 times and I still get the same error.

**Comment by theMiddleBlue** [comment]
@monrorMe could you provide the output of the following command?

```bash
$ docker exec -ti webmap /opt/nmapdashboard/nmapreport/token.py
```

**Comment by monrorMe** [comment]
I question! Where use the token when it is generated?  This may be the step I am missing?

**Comment by danyfu** [comment]
Use the token on the input, and then click on the login button.

![image](https://user-images.githubusercontent.com/9112457/50176258-c3452180-02b3-11e9-8d87-8cde86368480.png)

**Comment by monrorMe** [comment]
When I click  the login button I get Error Invalid token.

**Comment by monrorMe** [comment]
I don't get a input field to enter the token.

**Comment by monrorMe** [comment]
I see now thanks

**Comment by theMiddleBlue** [comment]
closed. Thanks @danyfu for help.
