### ISSUE TITLE
Python code cleanup to conform to PEP-8 and black formatting specifications

### ISSUE THREAD

**Issue by derpadoo** [Rev3rseSecurity/WebMap#77]
The project looks great and I appreciate the time you've put in to it!  I maintain Scantron (https://github.com/rackerlabs/scantron) which is a distributed nmap/masscan framework and would like to integrate some of the nice GUI and functionality of this project into that one.  

Taking a look at the code, I noticed a couple of areas to improve the readability and aesthetics of the Python code.  The first is to embrace the PEP-8 coding standard (https://www.python.org/dev/peps/pep-0008/), which, for example, prefers spaces or tabs.  I've seen both in some of the WebMap .py files.  The second is to consider using `black`, the "uncompromising Python code formatter" (https://github.com/ambv/black), which standardizes the formatting (for example, it prefers double quotes over single), so that the codes looks clean and consistent.  VS code has a built in plugin to assist in formatting with `black`.

If you're ok with that, I can submit a couple of pull requests so you can see the difference (it'd be pretty drastic at first).  These changes are purely aesthetic and don't change the functionality.  I didn't want to just start submitting PRs with massive changes.

Thanks again for providing this tool to the community!

**Comment by theMiddleBlue** [comment]
thanks @derpadoo 

> If you're ok with that, I can submit a couple of pull requests so you can see the difference (it'd be pretty drastic at first). These changes are purely aesthetic and don't change the functionality. I didn't want to just start submitting PRs with massive changes.

It would be really useful! any help on WebMap code is appreciated since I'm not so skilled on Django.

**Comment by derpadoo** [comment]
Cool, submitted a few.  Check out Two Scoops of Django for some best practices https://www.amazon.com/Two-Scoops-Django-1-11-Practices/dp/0692915729
