### ISSUE TITLE
Token issue

### ISSUE THREAD

**Issue by choupit0** [Rev3rseSecurity/WebMap#81]
Hello,

Sorry, it's not really an issue. In fact, I can't launch the Web application, I always have the same answer:

"Generate a new token with:
docker exec -ti webmap /root/token"

I well generated the token:

sudo docker exec -ti webmap /root/token
Token: TFaWMfmpCSRp

And I'm trying to use it:

http://192.168.2.10:8000/?token=TFaWMfmpCSRp

What's wrong? Bad URL? Thanks for your help!

Choupit0

**Comment by theMiddleBlue** [comment]
Hi @choupit0 

you should copy and paste the token in the input text of the login form and then click on "login" (is the only input text you have on the WebMap UI):

![image](https://user-images.githubusercontent.com/4454961/52240506-4a387280-28d1-11e9-8129-5c24b5eff95e.png)

**Comment by choupit0** [comment]
I'm so stupid.... I didn't know/see it was an input text...

Thank you!
